/* Quelle: Wikipedia "Spiel des Jahres" (de/en), Stand September 2026.
   BGG-Bewertung/Schwierigkeit/Dauer/Spieleranzahl/Alter werden beim Laden
   live über die BGG-XML-API nachgeladen (siehe assets/bgg.js). */

const SDJ_CATEGORIES = [
  { key: 'sdj', label: 'Spiel des Jahres', badgeClass: 'badge-sdj', color: 'var(--poeppel-rot)' },
  { key: 'kenner', label: 'Kennerspiel des Jahres', badgeClass: 'badge-kenner', color: 'var(--poeppel-anthrazit)' },
  { key: 'kinder', label: 'Kinderspiel des Jahres', badgeClass: 'badge-kinder', color: 'var(--poeppel-blau)' },
  { key: 'kinder-vor', label: 'Sonderpreis Kinderspiel (bis 2000)', badgeClass: 'badge-vorlaeufer', color: 'var(--cl-ink-soft)' }
];

function g(id, title, year, cat, designer, publisher, bggQuery) {
  const c = SDJ_CATEGORIES.find(x => x.key === cat);
  return { id, title, year, catKey: cat, catLabel: c.label, catBadgeClass: c.badgeClass, designer, publisher, bggQuery };
}

const SDJ_GAMES = [
  // ---------- Spiel des Jahres 1979–2025 ----------
  g('sdj-1979', 'Hase und Igel', 1979, 'sdj', 'David Parlett', 'Ravensburger'),
  g('sdj-1980', 'Rummikub', 1980, 'sdj', 'Ephraim Hertzano', 'Intelli'),
  g('sdj-1981', 'Focus', 1981, 'sdj', 'Sid Sackson', 'Parker'),
  g('sdj-1982', 'Sagaland', 1982, 'sdj', 'Alex Randolph, Michael Matschoss', 'Ravensburger', 'Sagaland Enchanted Forest'),
  g('sdj-1983', 'Scotland Yard', 1983, 'sdj', 'Manfred Burggraf u. a.', 'Ravensburger'),
  g('sdj-1984', 'Dampfroß', 1984, 'sdj', 'David Watts', 'Schmidt Spiele', 'Dampfross Railway Rivals'),
  g('sdj-1985', 'Sherlock Holmes Criminal-Cabinett', 1985, 'sdj', 'Raymond Edwards, Suzanne Goldberg, Gary Grady', 'Kosmos', 'Sherlock Holmes Consulting Detective'),
  g('sdj-1986', 'Heimlich & Co.', 1986, 'sdj', 'Wolfgang Kramer', 'Ravensburger', 'Heimlich and Co Top Secret Spies'),
  g('sdj-1987', 'Auf Achse', 1987, 'sdj', 'Wolfgang Kramer', 'F.X. Schmid'),
  g('sdj-1988', 'Barbarossa', 1988, 'sdj', 'Klaus Teuber', 'Otto Maier / Franjos', 'Barbarossa and the Sunken Treasure'),
  g('sdj-1989', 'Café International', 1989, 'sdj', 'Rudi Hoffmann', 'Mattel'),
  g('sdj-1990', 'Adel Verpflichtet', 1990, 'sdj', 'Klaus Teuber', 'F.X. Schmid'),
  g('sdj-1991', 'Drunter und Drüber', 1991, 'sdj', 'Klaus Teuber', 'Hans im Glück'),
  g('sdj-1992', 'Um Reifenbreite', 1992, 'sdj', 'Rob Bontenbal', 'Jumbo'),
  g('sdj-1993', 'Bluff', 1993, 'sdj', 'Richard Borg', 'F.X. Schmid'),
  g('sdj-1994', 'Manhattan', 1994, 'sdj', 'Andreas Seyfarth', 'Hans im Glück'),
  g('sdj-1995', 'Die Siedler von Catan', 1995, 'sdj', 'Klaus Teuber', 'Kosmos'),
  g('sdj-1996', 'El Grande', 1996, 'sdj', 'Wolfgang Kramer, Richard Ulrich', 'Hans im Glück'),
  g('sdj-1997', 'Mississippi Queen', 1997, 'sdj', 'Werner Hodel', 'Goldsieber'),
  g('sdj-1998', 'Elfenland', 1998, 'sdj', 'Alan R. Moon', 'Amigo'),
  g('sdj-1999', 'Tikal', 1999, 'sdj', 'Wolfgang Kramer, Michael Kiesling', 'Ravensburger'),
  g('sdj-2000', 'Torres', 2000, 'sdj', 'Wolfgang Kramer, Michael Kiesling', 'Ravensburger'),
  g('sdj-2001', 'Carcassonne', 2001, 'sdj', 'Klaus-Jürgen Wrede', 'Hans im Glück'),
  g('sdj-2002', 'Villa Paletti', 2002, 'sdj', 'Bill Payne', 'Zoch'),
  g('sdj-2003', 'Alhambra', 2003, 'sdj', 'Dirk Henn', 'Queen Games'),
  g('sdj-2004', 'Zug um Zug', 2004, 'sdj', 'Alan R. Moon', 'Days of Wonder', 'Ticket to Ride'),
  g('sdj-2005', 'Niagara', 2005, 'sdj', 'Thomas Liesching', 'Zoch'),
  g('sdj-2006', 'Thurn und Taxis', 2006, 'sdj', 'Andreas Seyfarth, Karen Seyfarth', 'Hans im Glück'),
  g('sdj-2007', 'Zooloretto', 2007, 'sdj', 'Michael Schacht', 'Abacus'),
  g('sdj-2008', 'Keltis', 2008, 'sdj', 'Reiner Knizia', 'Kosmos'),
  g('sdj-2009', 'Dominion', 2009, 'sdj', 'Donald X. Vaccarino', 'Hans im Glück'),
  g('sdj-2010', 'Dixit', 2010, 'sdj', 'Jean-Louis Roubira', 'Libellud'),
  g('sdj-2011', 'Qwirkle', 2011, 'sdj', 'Susan McKinley Ross', 'Schmidt Spiele'),
  g('sdj-2012', 'Kingdom Builder', 2012, 'sdj', 'Donald X. Vaccarino', 'Queen Games'),
  g('sdj-2013', 'Hanabi', 2013, 'sdj', 'Antoine Bauza', 'Abacus'),
  g('sdj-2014', 'Camel Up', 2014, 'sdj', 'Steffen Bogen', 'Eggertspiele'),
  g('sdj-2015', 'Colt Express', 2015, 'sdj', 'Christophe Raimbault', 'Ludonaute'),
  g('sdj-2016', 'Codenames', 2016, 'sdj', 'Vlaada Chvátil', 'Czech Games Edition'),
  g('sdj-2017', 'Kingdomino', 2017, 'sdj', 'Bruno Cathala', 'Pegasus Spiele'),
  g('sdj-2018', 'Azul', 2018, 'sdj', 'Michael Kiesling', 'Next Move Games'),
  g('sdj-2019', 'Just One', 2019, 'sdj', 'Ludovic Roudy, Bruno Sautter', 'Repos Production'),
  g('sdj-2020', 'Pictures', 2020, 'sdj', 'Daniela Stöhr, Christian Stöhr', 'PD-Verlag'),
  g('sdj-2021', 'MicroMacro: Crime City', 2021, 'sdj', 'Johannes Sich', 'Edition Spielwiese/Pegasus'),
  g('sdj-2022', 'Cascadia', 2022, 'sdj', 'Randy Flynn', 'Kosmos'),
  g('sdj-2023', 'Dorfromantik: Das Brettspiel', 2023, 'sdj', 'Michael Palm, Lukas Zach', 'Pegasus Spiele', 'Dorfromantik The Board Game'),
  g('sdj-2024', 'Sky Team', 2024, 'sdj', 'Luc Rémond', 'Kosmos/Scorpion Masqué'),
  g('sdj-2025', 'Bomb Busters', 2025, 'sdj', 'Hisashi Hayashi', 'Pegasus Spiele'),

  // ---------- Kennerspiel des Jahres 2011–2025 ----------
  g('kenner-2011', '7 Wonders', 2011, 'kenner', 'Antoine Bauza', 'Repos Production'),
  g('kenner-2012', 'Village', 2012, 'kenner', 'Inka Brand, Markus Brand', 'eggertspiele/Pegasus'),
  g('kenner-2013', 'Die Legenden von Andor', 2013, 'kenner', 'Michael Menzel', 'Kosmos'),
  g('kenner-2014', 'Istanbul', 2014, 'kenner', 'Rüdiger Dorn', 'Pegasus Spiele'),
  g('kenner-2015', 'Broom Service', 2015, 'kenner', 'Andreas Pelikan, Alexander Pfister', 'Ravensburger'),
  g('kenner-2016', 'Isle of Skye: Vom Häuptling zum König', 2016, 'kenner', 'Andreas Pelikan, Alexander Pfister', 'Lookout Games'),
  g('kenner-2017', 'EXIT – Das Spiel', 2017, 'kenner', 'Inka Brand, Markus Brand', 'Kosmos', 'Exit The Game'),
  g('kenner-2018', 'Die Quacksalber von Quedlinburg', 2018, 'kenner', 'Wolfgang Warsch', 'Schmidt Spiele', 'The Quacks of Quedlinburg'),
  g('kenner-2019', 'Flügelschlag', 2019, 'kenner', 'Elizabeth Hargrave', 'Feuerland Spiele', 'Wingspan'),
  g('kenner-2020', 'Die Crew: Reise zum 9. Planeten', 2020, 'kenner', 'Thomas Sing', 'Kosmos', 'The Crew Quest for Planet Nine'),
  g('kenner-2021', 'Paleo', 2021, 'kenner', 'Peter Rustemeyer', 'Hans im Glück'),
  g('kenner-2022', 'Living Forest', 2022, 'kenner', 'Aske Christiansen', 'Pegasus Spiele/Ludonaute'),
  g('kenner-2023', 'Challengers!', 2023, 'kenner', 'Johannes Krenner, Markus Slawitschek', '1 More Time Games'),
  g('kenner-2024', 'e-Mission', 2024, 'kenner', 'Matt Leacock, Matteo Menapace', 'Schmidt Spiele', 'Daybreak'),
  g('kenner-2025', 'Endeavor: Die Tiefsee', 2025, 'kenner', 'Carl de Visser, Jarratt Gray', 'Frosted Games', 'Endeavor Deep Sea'),

  // ---------- Kinderspiel des Jahres (offiziell) 2001–2025 ----------
  g('kinder-2001', 'Klondike', 2001, 'kinder', 'Christian Wolf, Stefanie Rohner', 'Habermaaß'),
  g('kinder-2002', 'Maskenball der Käfer', 2002, 'kinder', 'Peter-Paul Joopen', 'Selecta'),
  g('kinder-2003', 'Viva Topo!', 2003, 'kinder', 'Manfred Ludwig', 'Selecta'),
  g('kinder-2004', 'Geistertreppe', 2004, 'kinder', 'Michelle Schanen', 'Drei Magier Spiele'),
  g('kinder-2005', 'Das kleine Gespenst', 2005, 'kinder', 'Kai Haferkamp', 'Kosmos'),
  g('kinder-2006', 'Der schwarze Pirat', 2006, 'kinder', 'Guido Hoffmann', 'Habermaaß'),
  g('kinder-2007', 'Beppo der Bock', 2007, 'kinder', 'Peter Schackert', 'Huch & friends'),
  g('kinder-2008', 'Wer war\u2019s?', 2008, 'kinder', 'Reiner Knizia', 'Ravensburger', 'Wer wars Whoowasit'),
  g('kinder-2009', 'Das magische Labyrinth', 2009, 'kinder', 'Dirk Baumann', 'Drei Magier Spiele'),
  g('kinder-2010', 'Diego Drachenzahn', 2010, 'kinder', 'Manfred Ludwig', 'HABA'),
  g('kinder-2011', 'Da ist der Wurm drin', 2011, 'kinder', 'Carmen Kleinert', 'Zoch'),
  g('kinder-2012', 'Schnappt Hubi!', 2012, 'kinder', 'Steffen Bogen', 'Ravensburger'),
  g('kinder-2013', 'Der verzauberte Turm', 2013, 'kinder', 'Inka Brand, Markus Brand', 'Schmidt Spiele'),
  g('kinder-2014', 'Geister, Geister, Schatzsuchmeister!', 2014, 'kinder', 'Brian Yu', 'Mattel', 'Ghost Fightin Treasure Hunters'),
  g('kinder-2015', 'Spinderella', 2015, 'kinder', 'Roberto Fraga', 'Zoch'),
  g('kinder-2016', 'Mein erstes Steinzeitspiel', 2016, 'kinder', 'Marco Teubner', 'Hans im Glück', 'My First Stone Age'),
  g('kinder-2017', 'ICECOOL', 2017, 'kinder', 'Brian Gomez', 'Amigo', 'Icecool'),
  g('kinder-2018', 'Funkelschatz', 2018, 'kinder', 'Lena Burkhardt, Günter Burkhardt', 'HABA', 'Funkelschatz Dragons Breath'),
  g('kinder-2019', 'Tal der Wikinger', 2019, 'kinder', 'Marie Fort, Wilfried Fort', 'HABA', 'Valley of the Vikings'),
  g('kinder-2020', 'Speedy Roll', 2020, 'kinder', 'Urtis Šulinskas', 'Piatnik', 'Hedgehog Roll'),
  g('kinder-2021', 'Dragomino', 2021, 'kinder', 'Bruno Cathala, Marie Fort, Wilfried Fort', 'Pegasus Spiele/Blue Orange'),
  g('kinder-2022', 'Zauberberg', 2022, 'kinder', 'Jens-Peter Schliemann, Bernhard Weber', 'Amigo', 'Zauberberg Magic Mountain'),
  g('kinder-2023', 'Mysterium Kids', 2023, 'kinder', 'Antonin Boccara, Yves Hirschfeld', 'Libellud/Space Cow'),
  g('kinder-2024', 'Die magischen Schlüssel', 2024, 'kinder', 'Markus Slawitschek, Arno Steinwender', 'Game Factory', 'Magic Keys'),
  g('kinder-2025', 'Topp die Torte!', 2025, 'kinder', 'Wolfgang Warsch', 'Schmidt Spiele', 'Top the Cake'),

  // ---------- Vorläufer: Sonderpreis Kinderspiel 1989–2000 ----------
  g('kinderv-1989', 'Gute Freunde', 1989, 'kinder-vor', 'Alex Randolph', 'Selecta'),
  g('kinderv-1990', 'Das Geisterschloss', 1990, 'kinder-vor', 'Virginia Charves', 'F.X. Schmid'),
  g('kinderv-1991', 'Corsaro – Irrfahrt im Piratenmeer', 1991, 'kinder-vor', 'Wolfgang Kramer', 'Herder'),
  g('kinderv-1992', 'Schweinsgalopp', 1992, 'kinder-vor', 'Heinz Meister', 'Ravensburger', 'Galloping Pigs'),
  g('kinderv-1993', 'Ringel Rangel', 1993, 'kinder-vor', 'Geni Wyss', 'Habermaaß'),
  g('kinderv-1994', 'Looping Louie', 1994, 'kinder-vor', 'Carol Wiseley u. a.', 'Milton Bradley', 'Loopin Louie'),
  g('kinderv-1995', 'Karambolage', 1995, 'kinder-vor', 'Heinz Meister', 'Habermaaß'),
  g('kinderv-1996', 'Vier zu mir!', 1996, 'kinder-vor', 'Heike Baum', 'ASS Altenburger', 'Noahs Park'),
  g('kinderv-1997', 'Leinen los!', 1997, 'kinder-vor', 'Alex Randolph', 'Habermaaß'),
  g('kinderv-1998', 'Zicke Zacke Hühnerkacke', 1998, 'kinder-vor', 'Klaus Zoch', 'Zoch', 'Chicken Cha Cha Cha'),
  g('kinderv-1999', 'Kayanak', 1999, 'kinder-vor', 'Peter-Paul Joopen', 'Habermaaß'),
  g('kinderv-2000', 'Arbos', 2000, 'kinder-vor', 'Armin Müller, Martin Arnold', 'M+A Spiel')
];
